### ISSUE TITLE
python documentation tests failing

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10834]
## Rationale

The python tests are failing in PR #10832 , PR #10726 , PR #10833 .  Could someone please invalidate those tests when this issue is fixed?

## Description

The test output is:

```
MooseDocs:listings.basic: Working Directory: /opt/civet/build_0/moose/python/MooseDocs/tests/listings
MooseDocs:listings.basic: Running command: python -m unittest -v test_listings
MooseDocs:listings.basic: testCaption (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testCaptionId (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testContentError (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testDefault (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testDefaultNoButton (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testDisableStripExtraNewLines (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testDisableStripHeader (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testDisableStripLeadingWhitespace (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testEnd (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testFenced (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testFileError (test_listings.TestListings) ... ERROR
MooseDocs:listings.basic: testIndent (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testInputListing (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testLanguage (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testLine (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testListingMainComment (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testListingTick (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testPrefixSuffix (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testRef (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testStart (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testStartEnd (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testStartEndIncludeEnd (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testStripExtraNewLines (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testStripHeader (test_listings.TestListings) ... ok
MooseDocs:listings.basic: testStripLeadingWhitespace (test_listings.TestListings) ... ok
MooseDocs:listings.basic: 
MooseDocs:listings.basic: ======================================================================
MooseDocs:listings.basic: ERROR: testFileError (test_listings.TestListings)
MooseDocs:listings.basic: ----------------------------------------------------------------------
MooseDocs:listings.basic: Traceback (most recent call last):
MooseDocs:listings.basic:   File "test_listings.py", line 54, in testFileError
MooseDocs:listings.basic:   File "/opt/civet/build_0/moose/python/MooseDocs/testing.py", line 179, in assertConvert
MooseDocs:listings.basic:     fid.write(self.parser.convert(md_text))
MooseDocs:listings.basic:   File "/opt/civet/build_0/moose/python/MooseDocs/MooseMarkdown.py", line 133, in convert
MooseDocs:listings.basic:     return super(MooseMarkdown, self).convert(self.current.content)
MooseDocs:listings.basic:   File "/opt/moose/miniconda/lib/python2.7/site-packages/markdown/__init__.py", line 375, in convert
MooseDocs:listings.basic:     newRoot = treeprocessor.run(root)
MooseDocs:listings.basic:   File "/opt/moose/miniconda/lib/python2.7/site-packages/markdown/treeprocessors.py", line 324, in run
MooseDocs:listings.basic:     self.__handleInline(text), child
MooseDocs:listings.basic:   File "/opt/moose/miniconda/lib/python2.7/site-packages/markdown/treeprocessors.py", line 107, in __handleInline
MooseDocs:listings.basic:     data, patternIndex, startIndex)
MooseDocs:listings.basic:   File "/opt/moose/miniconda/lib/python2.7/site-packages/markdown/treeprocessors.py", line 245, in __applyPattern
MooseDocs:listings.basic:     node = pattern.handleMatch(match)
MooseDocs:listings.basic:   File "/opt/civet/build_0/moose/python/MooseDocs/extensions/listings.py", line 151, in handleMatch
MooseDocs:listings.basic:     content = self.extractContent(filename, settings)
MooseDocs:listings.basic:   File "/opt/civet/build_0/moose/python/MooseDocs/extensions/listings.py", line 354, in extractContent
MooseDocs:listings.basic:     return super(ListingInputPattern, self).extractContent(filename, settings)
MooseDocs:listings.basic:   File "/opt/civet/build_0/moose/python/MooseDocs/extensions/listings.py", line 266, in extractContent
MooseDocs:listings.basic:     with open(filename) as fid:
MooseDocs:listings.basic: IOError: [Errno 21] Is a directory: u'/opt/civet/build_0/moose/test/tests'
MooseDocs:listings.basic: 
MooseDocs:listings.basic: ----------------------------------------------------------------------
MooseDocs:listings.basic: Ran 25 tests in 0.403s
MooseDocs:listings.basic: 
MooseDocs:listings.basic: FAILED (errors=1)
MooseDocs:listings.basic: 
MooseDocs:listings.basic: ################################################################################
MooseDocs:listings.basic: Tester failed, reason: CRASH
MooseDocs:listings.basic: 
    FAIL MooseDocs:listings.basic FAILED (CRASH)
```

**Comment by permcody** [comment]
Fixed and all PRs with affected tests have been invalidated
