### ISSUE TITLE
Random test failure in MooseDocs/test/common.class_database

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#11043]
## Rationale

I have seen this test fail sporadically.

## Description

```
MooseDocs/test/common.class_database: Working Directory: /opt/civet/build_0/moose/python/MooseDocs/test/common
MooseDocs/test/common.class_database: Running command: python -m unittest -v test_database
MooseDocs/test/common.class_database: ERROR
MooseDocs/test/common.class_database: 
MooseDocs/test/common.class_database: ======================================================================
MooseDocs/test/common.class_database: ERROR: setUpClass (test_database.TestClassDatabase)
MooseDocs/test/common.class_database: ----------------------------------------------------------------------
MooseDocs/test/common.class_database: Traceback (most recent call last):
MooseDocs/test/common.class_database:   File "test_database.py", line 21, in setUpClass
MooseDocs/test/common.class_database:     cls.database = build_class_database('${MOOSE_DIR}/framework/include', '${MOOSE_DIR}/test/tests')
MooseDocs/test/common.class_database:   File "/opt/civet/build_0/moose/python/MooseDocs/common/build_class_database.py", line 51, in build_class_database
MooseDocs/test/common.class_database:     _process(objects, inputs, INPUT_RE, _match_input)
MooseDocs/test/common.class_database:   File "/opt/civet/build_0/moose/python/MooseDocs/common/build_class_database.py", line 69, in _process
MooseDocs/test/common.class_database:     with open(filename, 'r') as fid:
MooseDocs/test/common.class_database: IOError: [Errno 2] No such file or directory: '/opt/civet/build_0/moose/test/tests/test_harness/job_unittesting_pbs/exodiff_diff_gold.i'
MooseDocs/test/common.class_database: 
MooseDocs/test/common.class_database: ----------------------------------------------------------------------
MooseDocs/test/common.class_database: Ran 0 tests in 0.817s
MooseDocs/test/common.class_database: 
MooseDocs/test/common.class_database: FAILED (errors=1)
MooseDocs/test/common.class_database: 
MooseDocs/test/common.class_database: ################################################################################
MooseDocs/test/common.class_database: Tester failed, reason: CRASH
MooseDocs/test/common.class_database: 
    FAIL MooseDocs/test/common.class_database FAILED (CRASH)
```

## Impact

More robust testing.

**Comment by aeslaughter** [comment]
This can be fixed by using 'git ls-files', I will add it in to my next PR.
