### ISSUE TITLE
run_tests doesn't work without miniconda because of yaml

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#11186]
## Rationale

```
$ module unload miniconda
$ ./run_tests -j12
Traceback (most recent call last):
  File "./run_tests", line 7, in <module>
    from TestHarness import TestHarness
  File "/Users/slauae/projects/moose/python/TestHarness/__init__.py", line 10, in <module>
    from TestHarness import TestHarness
  File "/Users/slauae/projects/moose/python/TestHarness/TestHarness.py", line 22, in <module>
    import util
  File "/Users/slauae/projects/moose/python/TestHarness/util.py", line 12, in <module>
    from mooseutils import colorText
  File "/Users/slauae/projects/moose/python/mooseutils/__init__.py", line 17, in <module>
    from yaml_load import yaml_load
  File "/Users/slauae/projects/moose/python/mooseutils/yaml_load.py", line 18, in <module>
    import yaml
ImportError: No module named yaml
```

## Description
The `import yaml` should be moved inside the function so that it is only called if used. This is only used by MooseDocs.

## Impact
This will allow the test harness to run without miniconda.

**Comment by brianmoose** [comment]
`yaml_load.py` uses the yaml module all over the place, even at the module level.
@aeslaughter How would you feel about just removing `yaml_load` from `mooseutils/__init__.py` and just loading it in MooseDocs when you need it?
