### ISSUE TITLE
moosedocs "check" not working

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#11375]
## Rationale

`./moosedocs.py check --generate` should find new files that need to get created and create them.  But it's not in this case.

## Description

I added a new `TimeIntegrator` and I get the following:

```
[gastdr][~/projects/moose/test/doc]> ./moosedocs.py build
MooseDocs.extensions.appsyntax: Reading MOOSE application syntax.
MooseDocs.extensions.appsyntax: Building MOOSE class database.
MooseDocs.Translator: Building Pages...
MooseDocs.base.renderers: 
ERROR:The following errors were reported when accessing the '/Executioner/TimeIntegrator' syntax.

Failed to locate a page with the given filename: Executioner/TimeIntegrator/ActuallyExplicitEuler.md
/Users/gastdr/projects/moose/framework/doc/content/documentation/systems/index.md:1
 ┌─────────────────────────────────────────────────────────────────────────────────────────────────┐
1│                                                                                                 │
2│                                                                                                 │
 └─────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "/Users/gastdr/projects/moose/python/MooseDocs/base/renderers.py", line 107, in process
    el = func(token, parent) if func else parent
  File "/Users/gastdr/projects/moose/python/MooseDocs/extensions/appsyntax.py", line 431, in createMaterialize
    raise exceptions.RenderException(token.info, msg, token.syntax.fullpath)
RenderException: The following errors were reported when accessing the '/Executioner/TimeIntegrator' syntax.

Failed to locate a page with the given filename: Executioner/TimeIntegrator/ActuallyExplicitEuler.md


MooseDocs.base.renderers: 
ERROR:The following errors were reported when accessing the '/Executioner/TimeIntegrator' syntax.

Failed to locate a page with the given filename: Executioner/TimeIntegrator/ActuallyExplicitEuler.md
/Users/gastdr/projects/moose/framework/doc/content/documentation/systems/Executioner/TimeIntegrator/index.md:4
 ┌─────────────────────────────────────────────────────────────────────────────────────────────────┐
4│                                                                                                 │
5│                                                                                                 │
6│!syntax list /Executioner/TimeIntegrator objects=True actions=False subsystems=False             │
 └─────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "/Users/gastdr/projects/moose/python/MooseDocs/base/renderers.py", line 107, in process
    el = func(token, parent) if func else parent
  File "/Users/gastdr/projects/moose/python/MooseDocs/extensions/appsyntax.py", line 431, in createMaterialize
    raise exceptions.RenderException(token.info, msg, token.syntax.fullpath)
RenderException: The following errors were reported when accessing the '/Executioner/TimeIntegrator' syntax.

Failed to locate a page with the given filename: Executioner/TimeIntegrator/ActuallyExplicitEuler.md


MooseDocs.Translator: Build time 38.4573488235 sec.
CRITICAL:0 ERROR:2 WARNING:0
[gastdr][~/projects/moose/test/doc]> ./moosedocs.py check
MooseDocs.extensions.appsyntax: Reading MOOSE application syntax.
MooseDocs.extensions.appsyntax: Building MOOSE class database.
CRITICAL:0 ERROR:0 WARNING:0
```

So: `build` is seeing that files are missing but `check` is not.

## Impact

Just a speed bump to documentation generation

**Comment by friedmud** [comment]
Definitely still an issue:

```bash
[gastdr][~/projects/moose/test/doc]> ls /Users/gastdr/projects/moose/framework/doc/content/documentation/systems/Mesh/Partitioner/GridPartitioner.md
ls: /Users/gastdr/projects/moose/framework/doc/content/documentation/systems/Mesh/Partitioner/GridPartitioner.md: No such file or directory

[gastdr][~/projects/moose/test/doc]> ./moosedocs.py check --generate
MooseDocs.extensions.appsyntax: Reading MOOSE application syntax.
MooseDocs.extensions.appsyntax: Building MOOSE class database.
CRITICAL:0 ERROR:0 WARNING:0

[gastdr][~/projects/moose/test/doc]> ls /Users/gastdr/projects/moose/framework/doc/content/documentation/systems/Mesh/Partitioner/GridPartitioner.md
ls: /Users/gastdr/projects/moose/framework/doc/content/documentation/systems/Mesh/Partitioner/GridPartitioner.md: No such file or directory

[gastdr][~/projects/moose/test/doc]> ./moosedocs.py build
MooseDocs.extensions.appsyntax: Reading MOOSE application syntax.
MooseDocs.extensions.appsyntax: Building MOOSE class database.
MooseDocs.Translator: Building Pages...
MooseDocs.base.renderers: 
ERROR:The following errors were reported when accessing the '/Mesh/Partitioner' syntax.

Failed to locate a page with the given filename: Mesh/Partitioner/GridPartitioner.md
/Users/gastdr/projects/moose/framework/doc/content/documentation/systems/index.md:1
 ┌─────────────────────────────────────────────────────────────────────────────────────────────────┐
1│                                                                                                 │
2│                                                                                                 │
 └─────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "/Users/gastdr/projects/moose/python/MooseDocs/base/renderers.py", line 107, in process
    el = func(token, parent) if func else parent
  File "/Users/gastdr/projects/moose/python/MooseDocs/extensions/appsyntax.py", line 431, in createMaterialize
    raise exceptions.RenderException(token.info, msg, token.syntax.fullpath)
RenderException: The following errors were reported when accessing the '/Mesh/Partitioner' syntax.

Failed to locate a page with the given filename: Mesh/Partitioner/GridPartitioner.md
```

Notice: the file didn't exist before or after `check --generate` and `check` didn't show any errors or anything... but then `build` still printed an error.

I think the common thread here is that both this object and the `TimeIntegrator` this issue was originally about are both objects that go into "set" blocks... not sub-blocks of blocks (like Kernels).  This is a Partitioner so it goes in `[Mesh/Partitioner]`... do you think that could be it?  Maybe `check` isn't looking at those?

**Comment by dschwen** [comment]
> I think the common thread here is

This fails even for a simple AuxKernel

**Comment by aeslaughter** [comment]
I found the reason for this problem, it is a bit messy so it will take me a bit to get it worked out.

**Comment by dschwen** [comment]
This is still broken:

```
magpie/doc]> ./moosedocs.py check --generate
MooseDocs.extensions.appsyntax: Reading MOOSE application syntax.
MooseDocs.extensions.appsyntax: Building MOOSE class database.
CRITICAL:0 ERROR:0 WARNING:0
```

but 

```
magpie/doc]> ./moosedocs.py build --check
MooseDocs.extensions.appsyntax: Reading MOOSE application syntax.
MooseDocs.extensions.appsyntax: Building MOOSE class database.
MooseDocs.commands.check: No documentation for /Postprocessors/FourierLengthScale.
    - The page should be located at /Users/schwd/Programs/magpie/doc/content/source/postprocessors/FourierLengthScale.md.
    - It is possible to generate stub pages using './moosedocs.py check --generate'.
MooseDocs.commands.check: No documentation for /UserObjects/FourierTransform.
    - The page should be located at /Users/schwd/Programs/magpie/doc/content/source/userobjects/FourierTransform.md.
    - It is possible to generate stub pages using './moosedocs.py check --generate'.
MooseDocs.commands.check: No documentation for /VectorPostprocessors/FourierPowerSpectrum.
    - The page should be located at /Users/schwd/Programs/magpie/doc/content/source/vectorpostprocessors/FourierPowerSpectrum.md.
    - It is possible to generate stub pages using './moosedocs.py check --generate'.
MooseDocs.Translator: Building Pages...
MooseDocs.base.renderers:
...
```
(more errors follow)
