### ISSUE TITLE
moosedocs.py repr_str error

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#11808]
## Rationale

When doing ```moosedocs.py build --serve``` the doco builds fine, but doesn't properly continuously update due to a ```repr_str``` error.

## Description

```[I 180709 14:14:30 handlers:132] Browser Connected: http://127.0.0.1:8000/documentation/modules/porous_flow/boundaries.html
[E 180709 14:18:05 ioloop:792] Exception in callback <bound method type.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/opt/moose/miniconda/lib/python2.7/site-packages/tornado/ioloop.py", line 1208, in _run
        return self.callback()
      File "/opt/moose/miniconda/lib/python2.7/site-packages/livereload/handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/Users/wil04q/projects/moose/modules/doc/../../python/MooseDocs/commands/build.py", line 108, in examine
        return super(MooseDocsWatcher, self).examine()
      File "/opt/moose/miniconda/lib/python2.7/site-packages/livereload/watcher.py", line 92, in examine
        func.repr_str, delay))
    AttributeError: 'function' object has no attribute 'repr_str'
```

## Impact

Ability to continuously update webpages as i'm writing doco

**Comment by brianmoose** [comment]
I believe this is a known issue with `livereload` version 2.5.2. @aeslaughter can correct me if I am wrong and am getting my error messages confused.

You can downgrade it to 2.5.1 and it should work again.
Something like `sudo pip install -U livereload==2.5.1`
