### ISSUE TITLE
Peacock: Field Variable and Postprocessor (global) variables clash

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#11811]
## Rationale

Exodus supports having variables with the same name but different types but Peacock does not, we should allow this since MOOSE also supports it.

## Description

If you have a field variable and a postprocessor with the same name. MOOSE will write them out to the output file and they will show up correctly in Exodus viewers (Paraview), but those duplicate fields will not show up in either the Exodus viewer nor the Postprocessor window in peacock. 

## Impact

Minor: Peacock edge case (usability).

**Comment by cpgr** [comment]
I hit this today. Furthermore, if there is only one variable, and a postprocessor with the same name, then trying to open the exodus viewer causes a crash with the following
```
Traceback (most recent call last):
  File "/Users/gre462/Documents/MOOSE/projects/moose/python/peacock/ExodusViewer/plugins/ColorbarPlugin.py", line 135, in onUpdateWindow
    rng = result.getRange(local=self.ColorBarRangeType.isChecked())
  File "/Users/gre462/Documents/MOOSE/projects/moose/python/chigger/exodus/ExodusResult.py", line 90, in getRange
    rngs = [src.getRange(**kwargs) for src in self._sources]
  File "/Users/gre462/Documents/MOOSE/projects/moose/python/chigger/exodus/ExodusSource.py", line 124, in getRange
    raise mooseutils.MooseException("There must be a current variable for getRange.")
mooseutils.MooseException.MooseException: There must be a current variable for getRange.
```
