### ISSUE TITLE
GeneratedMesh bug

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#12679]
## Rationale

I get this error:
```
/apps/gcc/4.9.3/include/c++/4.9.3/debug/vector:357:error: attempt to
    subscript container with out-of-bounds index -4, but container only
    holds 5 elements.
```
with this trace:
```
#0  0x00007fffde0b1f67 in raise () from /lib64/libc.so.6
#1  0x00007fffde0b333a in abort () from /lib64/libc.so.6
#2  0x00007fffe42f22c5 in __gnu_debug::_Error_formatter::_M_error (this=0x7fffffffb0b0) at ../../../../../libstdc++-v3/src/c++11/debug.cc:782
#3  0x00007ffff75b32c9 in std::__debug::vector<double, std::allocator<double> >::operator[] (this=0xcac230, __n=18446744073709551612)
    at /apps/gcc/4.9.3/include/c++/4.9.3/debug/vector:357
#4  0x00007ffff3a98bc6 in GeneratedMesh::buildMesh (this=0xcadfd0) at /projects/cmrp/projects_wil04q/moose/framework/src/mesh/GeneratedMesh.C:263
#5  0x00007ffff3aad87f in MooseMesh::init (this=0xcadfd0) at /projects/cmrp/projects_wil04q/moose/framework/src/mesh/MooseMesh.C:2095
#6  0x00007ffff3d31c9d in SetupMeshAction::act (this=0xbc7930) at /projects/cmrp/projects_wil04q/moose/framework/src/actions/SetupMeshAction.C:223
#7  0x00007ffff3d09ced in Action::timedAct (this=0xbc7930) at /projects/cmrp/projects_wil04q/moose/framework/src/actions/Action.C:86
#8  0x00007ffff3d0db7b in ActionWarehouse::executeActionsWithAction (this=0xb58c30, task=...)
    at /projects/cmrp/projects_wil04q/moose/framework/src/actions/ActionWarehouse.C:361
#9  0x00007ffff3d0d777 in ActionWarehouse::executeAllActions (this=0xb58c30)
    at /projects/cmrp/projects_wil04q/moose/framework/src/actions/ActionWarehouse.C:338
#10 0x00007ffff418ab02 in MooseApp::runInputFile (this=0xb57c60) at /projects/cmrp/projects_wil04q/moose/framework/src/base/MooseApp.C:797
#11 0x00007ffff418b591 in MooseApp::run (this=0xb57c60) at /projects/cmrp/projects_wil04q/moose/framework/src/base/MooseApp.C:953
#12 0x000000000042024c in main (argc=3, argv=0x7fffffffc358) at /projects/cmrp/projects_wil04q/moose/modules/porous_flow/src/main.C:32
```
pointing to this line in GeneratedMesh.C:
```
            // Move node to biased location.
            node(dir) =
                mins[dir] + width[dir] * (1. - pows[dir][index]) / (1. - pows[dir][nelem[dir]]);
```

## Description

My input file is:
```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 3
  xmin = 0
  xmax = 1
  ny = 4
  ymin = -1
  ymax = 2
  bias_y = 1.5
  nz = 4
  zmin = 1
  zmax = 2
  bias_z = 0.8
[]

[Variables]
  [./pp]
  [../]
[]


[Kernels]
  [./pp]
    type = Diffusion
    variable = pp
  [../]
[]

[Executioner]
  type = Transient
  end_time = 1
  num_steps = 1
  dt = 1
[]

```
I am running using the `next` branch

**Comment by permcody** [comment]
Thanks for the report.

**Comment by permcody** [comment]
@idaholab/moose-team - If anybody needs a "break". This ticket looks like an easy one!

**Comment by permcody** [comment]
Crickets... Well, I'll work on this then.

**Comment by permcody** [comment]
Oh... Tricky! You "claim" to be building a 2D mesh, yet you provide "Z" related info... Nice try @WilkAndy!
That doesn't excuse the crash, but that's where the problem lies.

**Comment by permcody** [comment]
![3d_bias_mesh](https://user-images.githubusercontent.com/3036960/51060729-ee1e4f00-15ad-11e9-9448-8016d0592430.png)

I'm hardening that logic so you won't be able to break it so easily. Here's your mesh...

**Comment by WilkAndy** [comment]
Oh my goodness, i'm so sorry for the mesh mixup, @permcody.   Silly me.  I'm glad you had fun doing something easy for a change.
