### ISSUE TITLE
MooseDocs Build ImportError: No module named hit

### ISSUE THREAD

**Issue by dylanjm** [idaholab/moose#12933]
## Rationale

After updating MOOSE and Bison this morning, I attempted to build MooseDocs for Bison and got an error. 

## Description

The trace stack I am receiving when running `python moosedocs.py build --serve` is:

```
Traceback (most recent call last):
  File "moosedocs.py", line 23, in <module>
    from MooseDocs import main
  File "/Users/mcdodj/Documents/projects/bison/doc/../moose/python/MooseDocs/__init__.py", line 26, in <module>
    import mooseutils
  File "/Users/mcdodj/Documents/projects/bison/doc/../moose/python/mooseutils/__init__.py", line 17, in <module>
    from sqa_check import sqa_check, check_requirement
  File "/Users/mcdodj/Documents/projects/bison/doc/../moose/python/mooseutils/sqa_check.py", line 13, in <module>
    from hit_load import hit_load
  File "/Users/mcdodj/Documents/projects/bison/doc/../moose/python/mooseutils/hit_load.py", line 12, in <module>
    import hit
ImportError: No module named hit
```

I am running the MiniConda installation of Python
```
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

## Impact

Unable to build documentation.

**Comment by permcody** [comment]
You are going to need to recompile everything (MOOSE/BISON) after the update. I suspect that you didn't do this... HIT is built as part of that process (part of compiling the framework). However, under certain circumstances it's useful to build HIT without MOOSE at all (it is a general purpose file parser after all). So in the case where you only need hit, there's a separate Makefile target for it.

```
$ make hit
```

Before you do that though, make sure you have recompiled MOOSE/BISON and this error will likely go away.
