### ISSUE TITLE
Inform user when using invalid parameter name in test harness

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#14803]
## Reason
When a user incorrectly specifies a parameter name in a `tests` file, they should get an informative error message telling them they did so. Otherwise, it is very difficult to know this from the resulting stack trace. An example: we specified `timeout` instead of the correct name, `max_time`, so we get this stack trace (and there's no indication of which test is to blame):
```
Traceback (most recent call last):
  File "/Users/hansje/projects/relap-7/run_tests", line 19, in <module>
    TestHarness.buildAndRun(sys.argv, None, MOOSE_DIR)
  File "/Users/hansje/projects/relap-7/moose/python/TestHarness/TestHarness.py", line 51, in buildAndRun
    harness.findAndRunTests()
  File "/Users/hansje/projects/relap-7/moose/python/TestHarness/TestHarness.py", line 268, in findAndRunTests
    testers = self.createTesters(dirpath, file, find_only, testroot_params)
  File "/Users/hansje/projects/relap-7/moose/python/TestHarness/TestHarness.py", line 309, in createTesters
    parser.parse(file, testroot_params.get("root_params", self.root_params))
  File "/Users/hansje/projects/relap-7/moose/python/FactorySystem/Parser.py", line 64, in parse
    self._parseNode(filename, self.root, default_values)
  File "/Users/hansje/projects/relap-7/moose/python/FactorySystem/Parser.py", line 170, in _parseNode
    self._parseNode(filename, child, default_values)
  File "/Users/hansje/projects/relap-7/moose/python/FactorySystem/Parser.py", line 147, in _parseNode
    self.extractParams(filename, params, node)
  File "/Users/hansje/projects/relap-7/moose/python/FactorySystem/Parser.py", line 116, in extractParams
    self.error('unused parameter "{}"'.format(child.fullpath), node=child)
NameError: name 'child' is not defined
```

## Design
On an invalid name, I propose that we give an error message containing:
- The name of the invalid parameter
- The path of the faulty `tests` file
- The line number (or the test within the `tests` file)

## Impact
This will add an error message.

**Comment by aeslaughter** [comment]
Fixed by e0c9d3deaf1f237c7e98f90f666cb07c83161eae
