### ISSUE TITLE
moosedoc.py check --generate error with stochastic_tools 

### ISSUE THREAD

**Issue by iwhalvic** [idaholab/moose#16155]
## Bug Description
When attempting co call moosedocs.py check --generate StochasticToolsApp I get an error

```
(moose) ian@ian-blkbx:~/projects/moose/modules/stochastic_tools/doc$ ./moosedocs.py check --generate StochasticToolsApp
Traceback (most recent call last):
  File "./moosedocs.py", line 30, in <module>
    sys.exit(main.run())
  File "/home/ian/projects/moose/modules/stochastic_tools/doc/../../../python/MooseDocs/main.py", line 55, in run
    errno = check.main(options)
  File "/home/ian/projects/moose/modules/stochastic_tools/doc/../../../python/MooseDocs/commands/check.py", line 96, in main
    if (set(report.app_types) == set(opt.generate)):
TypeError: 'NoneType' object is not iterable
(moose) ian@ian-blkbx:~/projects/moose/module
```

Digging into moose/python/MooseDocs/commands/check.py the error seems to be here
```

 if app_reports and opt.generate:
        for report in app_reports:
            if (set(report.app_types) == set(opt.generate)):
                report.generate_stubs = True
```

report.app_types is None 
opt.generate = [stochastic_tools]

report is set in get_sqa_reports.py, here is the meat of that

 ```
app_configs = config['Applications']
    reports = list()
    for name, kwargs in app_configs.items():
        kwargs.setdefault('title', name)
        reports.append(SQAMooseAppReport(**kwargs))
```
the SQAMooseAppReport does get appended, but the `app_type` is never set. Looking at that class, it seems like app_types gets set when you execute, not initialize.

Note that `report.title=stochastic_tools,` so maybe it is as simple as using that instead of `app_types`. This is done in some other calls in check.py

```
    doc_reports, req_reports, app_reports = moosesqa.get_sqa_reports(opt.config, **kwargs)

    # Limit the reports
    if opt.app_reports and app_reports:
        app_reports = [report for report in app_reports if report.title in opt.app_reports]
    if opt.req_reports and req_reports:
        req_reports = [report for report in req_reports if report.title in opt.req_reports]

    # Apply --generate option
    if app_reports and opt.generate:
        for report in app_reports:
            if (set(report.app_types) == set(opt.generate)):
                report.generate_stubs = True
    # Apply --dump option
    if app_reports and opt.dump:
        for report in app_reports:
            if report.title in opt.dump:
                report.dump_syntax = True
```

## Steps to Reproduce
Attempt to generate Moosedoc stubs for StochasticToolsApp

`moosedocs.py check --generate StochasticToolsApp`

## Impact
Does not generate stubs for new object. I believe this is causing documentation test failures for my PR #15736

**Comment by iwhalvic** [comment]
@zachmprince 
@aeslaughter

**Comment by aeslaughter** [comment]
I will take a look
