### ISSUE TITLE
Error when trying to open an exodus mesh without a solution

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#1683]
If you try to open an input mesh with peacock - you get the following:
permcj@thearchitect { ...runk/moose_test/tests/kernels/2d_diffusion(work) }$ peacock -v square.e 
Using Executable: /Users/permcj/projects/trunk/moose_test/moose_test-opt
Traceback (most recent call last):
  File "/Users/permcj/projects/trunk/peacock/peacock", line 209, in <module>
    main_window = UiBox(options,args,executable,app)
  File "/Users/permcj/projects/trunk/peacock/peacock", line 54, in **init**
    self.initUI()
  File "/Users/permcj/projects/trunk/peacock/peacock", line 86, in initUI
    tab._openFile(options.visualize_result)
  File "/Users/permcj/projects/trunk/peacock/vtk/ExodusResultRenderWidget.py", line 698, in _openFile
    self._updateData()
  File "/Users/permcj/projects/trunk/peacock/vtk/ExodusResultRenderWidget.py", line 923, in _updateData
    self._timeSliderReleased()
  File "/Users/permcj/projects/trunk/peacock/vtk/ExodusResultRenderWidget.py", line 844, in _timeSliderReleased
    self._updateContours()
  File "/Users/permcj/projects/trunk/peacock/vtk/ExodusResultRenderWidget.py", line 610, in _updateContours
    if self.component_index == -1:
AttributeError: 'ExodusResultRenderWidget' object has no attribute 'component_index'

**Comment by permcody** [comment]
No documentation on why this was closed. Please reference a ticket or state the reason for closing.

**Comment by aeslaughter** [comment]
The new version of Peacock can open "mesh only" files.
