### ISSUE TITLE
Missing python package dependency on sampler test

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#17995]
## Bug Description
A test is ran when the required python package, tornado, in not installed

```
samplers/distribute.scale/execute: Working Directory: /gpfs/fs1/home/wuw/projects/moose/test/tests/samplers/distribute
samplers/distribute.scale/execute: Running command: /gpfs/fs1/home/wuw/projects/moose/test/tests/samplers/distribute/execute.py
samplers/distribute.scale/execute: Traceback (most recent call last):
samplers/distribute.scale/execute: File "/soft/oneAPI/2021.2.0.2883/intelpython/latest/lib/python3.7/site-packages/matplotlib/backends/backend_webagg.py", line 26, in
samplers/distribute.scale/execute: import tornado
samplers/distribute.scale/execute: ModuleNotFoundError: No module named 'tornado'
samplers/distribute.scale/execute:
samplers/distribute.scale/execute: During handling of the above exception, another exception occurred:
samplers/distribute.scale/execute:
samplers/distribute.scale/execute: Traceback (most recent call last):
samplers/distribute.scale/execute: File "/gpfs/fs1/home/wuw/projects/moose/test/tests/samplers/distribute/execute.py", line 6, in
samplers/distribute.scale/execute: import matplotlib.pyplot as plt
samplers/distribute.scale/execute: File "/soft/oneAPI/2021.2.0.2883/intelpython/latest/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2349, in
samplers/distribute.scale/execute: switch_backend(rcParams["backend"])
samplers/distribute.scale/execute: File "/soft/oneAPI/2021.2.0.2883/intelpython/latest/lib/python3.7/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
samplers/distribute.scale/execute: backend_mod = importlib.import_module(backend_name)
samplers/distribute.scale/execute: File "/soft/oneAPI/2021.2.0.2883/intelpython/latest/lib/python3.7/importlib/init.py", line 127, in import_module
samplers/distribute.scale/execute: return _bootstrap._gcd_import(name[level:], package, level)
samplers/distribute.scale/execute: File "/soft/oneAPI/2021.2.0.2883/intelpython/latest/lib/python3.7/site-packages/matplotlib/backends/backend_webagg.py", line 28, in
samplers/distribute.scale/execute: raise RuntimeError("The WebAgg backend requires Tornado.")
samplers/distribute.scale/execute: RuntimeError: The WebAgg backend requires Tornado.
samplers/distribute.scale/execute: Traceback (most recent call last):
samplers/distribute.scale/execute: File "/soft/oneAPI/2021.2.0.2883/intelpython/latest/lib/python3.7/site-packages/matplotlib/backends/backend_webagg.py", line 26, in
samplers/distribute.scale/execute: import tornado
samplers/distribute.scale/execute: ModuleNotFoundError: No module named 'tornado'
samplers/distribute.scale/execute:
samplers/distribute.scale/execute: During handling of the above exception, another exception occurred:
samplers/distribute.scale/execute:
samplers/distribute.scale/execute: Traceback (most recent call last):
samplers/distribute.scale/execute: File "/gpfs/fs1/home/wuw/projects/moose/test/tests/samplers/distribute/execute.py", line 6, in
samplers/distribute.scale/execute: import matplotlib.pyplot as plt
samplers/distribute.scale/execute: File "/soft/oneAPI/2021.2.0.2883/intelpython/latest/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2349, in
samplers/distribute.scale/execute: switch_backend(rcParams["backend"])
samplers/distribute.scale/execute: File "/soft/oneAPI/2021.2.0.2883/intelpython/latest/lib/python3.7/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
samplers/distribute.scale/execute: backend_mod = importlib.import_module(backend_name)
samplers/distribute.scale/execute: File "/soft/oneAPI/2021.2.0.2883/intelpython/latest/lib/python3.7/importlib/init.py", line 127, in import_module
samplers/distribute.scale/execute: return _bootstrap._gcd_import(name[level:], package, level)
samplers/distribute.scale/execute: File "/soft/oneAPI/2021.2.0.2883/intelpython/latest/lib/python3.7/site-packages/matplotlib/backends/backend_webagg.py", line 28, in
samplers/distribute.scale/execute: raise RuntimeError("The WebAgg backend requires Tornado.")
samplers/distribute.scale/execute: RuntimeError: The WebAgg backend requires Tornado.
samplers/distribute.scale/execute:
samplers/distribute.scale/execute:
samplers/distribute.scale/execute: Exit Code: 1
samplers/distribute.scale/execute: ################################################################################
samplers/distribute.scale/execute: Tester failed, reason: CRASH
samplers/distribute.scale/execute:
samplers/distribute.scale/execute ............................................................. FAILED (CRASH)
```

## Steps to Reproduce
Install moose, remove tornado, run tests

## Impact
A user had a test failure, which we investigated. Thanks @wuwenkun for taking the time

**Comment by GiudGiud** [comment]
Kind of a mpl/jupyter bug. we don't need tornado for our tests
