### ISSUE TITLE
TestHarness to understand submodule not present (SKIP specialized test)

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#20729]
## Reason
When an optional submodule is not present, the TestHarness should skip tests designed to test/require that specific submodule.

## Design
Add a check for the necessary requirements provided by a submodule

## Impact
Tests that fail horribly, will instead be appropriately skipped

**Comment by permcody** [comment]
If/when you start working on this - please talk to me first about design. I've been thinking about this quite a bit and have a few ideas.

**Comment by permcody** [comment]
That’s more of a question for you. Aren’t we failing a bunch of installed
tests every time we build?

**Comment by aarograh** [comment]
What's the status of this?  I am running into this issue as well since I have some coupled tests that should only run if the other apps are present alongside my main app.

**Comment by loganharbour** [comment]
> What's the status of this? I am running into this issue as well since I have some coupled tests that should only run if the other apps are present alongside my main app.

Are you installing your application or just building it in place? This issue is for the former. If you're not installing, `required_applications` and `required_submodule` are valid test spec options that currently work.

**Comment by aarograh** [comment]
> > What's the status of this? I am running into this issue as well since I have some coupled tests that should only run if the other apps are present alongside my main app.
> 
> Are you installing your application or just building it in place? This issue is for the former. If you're not installing, `required_applications` and `required_submodule` are valid test spec options that currently work.

That's exactly what I need right now (though I may need the installation version eventually).  Looks like it works as needed.  Where are these options documented?

**Comment by loganharbour** [comment]
> > > What's the status of this? I am running into this issue as well since I have some coupled tests that should only run if the other apps are present alongside my main app.
> > 
> > 
> > Are you installing your application or just building it in place? This issue is for the former. If you're not installing, `required_applications` and `required_submodule` are valid test spec options that currently work.
> 
> That's exactly what I need right now (though I may need the installation version eventually). Looks like it works as needed. Where are these options documented?

Not all options are documented well, unfortunately. But you can dump the entire set of parameters for each test type by running `./run_tests --dump`. Somewhere in there for each object you'll see something like this:

```
    required_applications          =                                # A list of required registered applications that are in the executable.
    required_objects               =                                # A list of required objects that are in the executable.
    required_python_packages       =                                # Test will only run if the supplied python packages exist.
    required_submodule             =                                # A list of initialized submodules for which this test requires.
```

**Comment by aarograh** [comment]
@loganharbour thanks for the tip.  That's good to know.

The `required_applications` option correctly disabled the tests when the other app is not present.  I just tried adding the app and rebuilding.  Things looked fine but when I ran the test script, I got the output below.  Any suggestions?  I made no modifications to the `run_tests` script.

```
./run_tests -j8
Traceback (most recent call last):
  File "/home/ag6/zoo/mole/./run_tests", line 12, in <module>
    TestHarness.buildAndRun(sys.argv, 'mole', MOOSE_DIR)
  File "/home/ag6/zoo/mole/moose/python/TestHarness/TestHarness.py", line 181, in buildAndRun
    harness.findAndRunTests()
  File "/home/ag6/zoo/mole/moose/python/TestHarness/TestHarness.py", line 424, in findAndRunTests
    self.scheduler.schedule(testers)
  File "/home/ag6/zoo/mole/moose/python/TestHarness/schedulers/Scheduler.py", line 221, in schedule
    j_dag = jobs.createJobs(testers)
  File "/home/ag6/zoo/mole/moose/python/TestHarness/JobDAG.py", line 56, in createJobs
    return self._checkDAG()
  File "/home/ag6/zoo/mole/moose/python/TestHarness/JobDAG.py", line 105, in _checkDAG
    self._doLast()
  File "/home/ag6/zoo/mole/moose/python/TestHarness/JobDAG.py", line 133, in _doLast
    self._doSkippedDependencies()
  File "/home/ag6/zoo/mole/moose/python/TestHarness/JobDAG.py", line 191, in _doSkippedDependencies
    if not job.getRunnable() or job.isFail() or job.isSkip():
  File "/home/ag6/zoo/mole/moose/python/TestHarness/schedulers/Job.py", line 153, in getRunnable
    return self.__tester.getRunnable(self.options)
  File "/home/ag6/zoo/mole/moose/python/TestHarness/testers/Tester.py", line 241, in getRunnable
    self._runnable = self.checkRunnableBase(options)
  File "/home/ag6/zoo/mole/moose/python/TestHarness/testers/Tester.py", line 614, in checkRunnableBase
    checks["registered_apps"] = util.getExeRegisteredApps(self.specs["executable"])
  File "/home/ag6/zoo/mole/moose/python/TestHarness/util.py", line 817, in getExeRegisteredApps
    data = getExeJSON(exe)
  File "/home/ag6/zoo/mole/moose/python/TestHarness/util.py", line 800, in getExeJSON
    output = output.split('**START JSON DATA**\n')[1]
IndexError: list index out of range
```

**Comment by milljm** [comment]
This could mean that your app is not outputing 'json' when the TestHarness calls for it. Can you try that manually?

```bash
your_app-opt --json
```

**Comment by milljm** [comment]
@permcody Looks like this got labeled by the stale bot of death. I placed a "DO NOT MERGE" label on it because I am sure we were not finished with it: https://github.com/idaholab/moose/pull/20968/files

However, it works for what small additions it does currently.
```bash
$> cd moose/test
$> make
$> cat .moose_test
registered_apps:
- MOOSETESTAPP
```

This is then read by the TestHarness:
```python
        if self.specs["required_applications"] and checks["registered_apps"] is None:
            checks["registered_apps"] = util.getExeRegisteredApps(self.specs["executable"])
            checks["registered_apps"] = util.getRegisteredApps(self.specs["executable"],
                                                               self.specs["app_name"])

        # Check to see if we have the required application names
        for var in self.specs['required_applications']:
            if var not in checks["registered_apps"]:
            if var.upper() not in checks["registered_apps"]:
                reasons['required_applications'] = 'App %s not registered in executable' % var
                break
```
