### ISSUE TITLE
MooseDocs fails to build MOOSE website using Python 3.10 on macOS

### ISSUE THREAD

**Issue by cticenhour** [idaholab/moose#21767]
## Bug Description
When using Python 3.10 with conda, MooseDocs fails to build the full MOOSE website, giving the following error: 
```
Traceback (most recent call last):
  File "/Users/icenct/projects/moose/modules/doc/./moosedocs.py", line 32, in <module>
    sys.exit(main.run())
  File "/Users/icenct/projects/moose/python/MooseDocs/main.py", line 57, in run
    errno = build.main(options)
  File "/Users/icenct/projects/moose/python/MooseDocs/commands/build.py", line 267, in main
    translator.execute(contents[index], num_threads=options.num_threads, render=False, write=False)
  File "/Users/icenct/projects/moose/python/MooseDocs/base/Translator.py", line 289, in execute
    self.__executioner(nodes or self.getPages(), num_threads, read, tokenize, render, write)
  File "/Users/icenct/projects/moose/python/MooseDocs/base/executioners.py", line 275, in __call__
    self.execute(source_nodes, n, read, tokenize, render, write)
  File "/Users/icenct/projects/moose/python/MooseDocs/base/executioners.py", line 461, in execute
    self._run(nodes, self._page_content, self._read_target, num_threads)
  File "/Users/icenct/projects/moose/python/MooseDocs/base/executioners.py", line 483, in _run
    self._ctx.Process(target=target, args=(page_queue, output_queue)).start()
  File "/Users/icenct/mambaforge3/envs/moose/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/icenct/mambaforge3/envs/moose/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/icenct/mambaforge3/envs/moose/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/icenct/mambaforge3/envs/moose/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/icenct/mambaforge3/envs/moose/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/icenct/mambaforge3/envs/moose/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'module' object
```

## Steps to Reproduce

```
conda create -n docs-fail -q -y
conda activate docs-fail
mamba install moose-libmesh=2022.06.06=build_4 moose-tools python=3.10
cd ~/projects/moose/modules
make -j8
cd doc
./moosedocs.py build
```
## Impact
This will stop anyone from using MooseDocs while using Python 3.10.

**Comment by cticenhour** [comment]
This does seem to be a macOS problem, as the Linux CI recipes seem to be already using Python 3.10.5 and not failing. 

Mac example: https://civet.inl.gov/job/1134419/
Linux example (from same next testing set): https://civet.inl.gov/job/1134420/
