### ISSUE TITLE
Strange behavior with CSVDiff with abs_zero

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#23522]
## Bug Description
When comparing two valid CSV files (one produced by running the test, the other representing the gold file), the test harness may print out something like

```
test:dummy.test: ERROR: Traceback (most recent call last):
test:dummy.test:   File "/home/anovak/moose/python/mooseutils/csvdiff.py", line 399, in <module>
test:dummy.test:     messages = csv_differ.diff()
test:dummy.test:   File "/home/anovak/moose/python/mooseutils/csvdiff.py", line 327, in diff
test:dummy.test:     table2[key].index(val2),
test:dummy.test: ValueError: 0 is not in list
```

when using `abs_zero` (but disappears when not using `abs_zero`). I think this may be happening if one of the numbers to be compared is above `abs_zero`, but the other is below it.

## Steps to Reproduce

I have attached a `test.i`, with a bunch of postprocessor values. I copied these verbatim from an actual Cardinal test we're seeing this problem with, which is why there's so many (wasn't sure which one was the culprit). Accompanying this is our actual `test_out.csv`. 

Run `./run_tests --re=dummy` to get the error. If you comment out `abs_zero`, the error goes away and instead shows the typical postprocessor diff summary.

## Impact
If this error is a manifestation of something wrong with our test itself, it would be helpful to understand what that may be. Otherwise, this is preventing a new feature being merged in Cardinal.

tag @anshchaube

**Comment by aprilnovak** [comment]
Gold file:

```
time,avg_T_diff,avg_Vx_diff,max_T,max_T_diff,max_Vx,max_Vx_diff,max_p,max_p_diff,min_T,min_T_diff,min_Vx,min_Vx_diff,min_p,min_p_diff,volume,volume_diff
0.1,0.00013204303442671,-1.2848881364424e-11,1.0066003667088,0.00013217974302737,3.1759999847289e-09,3.1759999847289e-09,2.3438291012104,-0.0024044303741566,1.0065999614685,0.00013177696605426,-3.3552608695131e-09,-3.3552608695131e-09,-1.1745162544756,-3.5207491349597,0.15,0.049999999999998
```

Tests file:

```
[Tests]
  [test]
    type = CSVDiff
    input = test.i
    csvdiff = test_out.csv
    abs_zero = 5e-7
  []
[]
```

**Comment by aprilnovak** [comment]
Input file:

```
[Problem]
  type = FEProblem
  solve = false
[]

[Mesh]
  type = GeneratedMesh
  dim = 1
[]

[Postprocessors]
  [avg_T_diff]
    type = Receiver
    default = 2.678039987547e-07
  []
  [avg_Vx_diff]
    type = Receiver
    default = 1.2512522098201e-11
  []
  [max_T]
    type = Receiver
    default = 1.0066003669779
  []
  [max_T_diff]
    type = Receiver
    default = 4.0459630601397e-07
  []
  [max_Vx]
    type = Receiver
    default = 6.7704981553449e-09
  []
  [max_Vx_diff]
    type = Receiver
    default = 6.7704981553449e-09
  []
  [max_p]
    type = Receiver
    default = 2.3438300208439
  []
  [max_p_diff]
    type = Receiver
    default = 1.3922019270751e-07
  []
  [min_T]
    type = Receiver
    default = 1.0065999605737
  []
  [min_T_diff]
    type = Receiver
    default = -1.9842372189771e-10
  []
  [min_Vx]
    type = Receiver
    default = -2.9778594441898e-09
  []
  [min_Vx_diff]
    type = Receiver
    default = -2.9778594441898e-09
  []
  [min_p]
    type = Receiver
    default = -1.1745155725556
  []
  [min_p_diff]
    type = Receiver
    default = -3.5183447774491
  []
  [volume]
    type = Receiver
    default = 0.15000000000001
  []
  [volume_diff]
    type = Receiver
    default = 0.050000000000007
  []
[]

[Outputs]
  csv = true
  execute_on = final
[]

[Executioner]
  type = Transient
  dt = 0.1
  num_steps = 1
[]
```

**Comment by permcody** [comment]
@GiudGiud - How do you want to finish up this PR? I could see if Elley may be able to work on it unless you have other plans.

**Comment by GiudGiud** [comment]
I had no plans to. Happy to help though. There will be some merge conflicts to deal with from a recent merge
