### ISSUE TITLE
Perflog option does not work for `SpeedTest`

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#23721]
## Bug Description
An error results if the `perflog` option is used for `SpeedTest`.

## Steps to Reproduce
Try setting `perflog = True` in test(s) in `test/tests/kernels/simple_transient_diffusion/speedtests` and then run
```
run_tests --run speedtests
```
I got the following error:
```
runWorker Exception: Traceback (most recent call last):
  File "/Users/hansje/projects/sockeye/moose/python/TestHarness/schedulers/RunParallel.py", line 53, in run
    job.run()
  File "/Users/hansje/projects/sockeye/moose/python/TestHarness/schedulers/Job.py", line 231, in run
    self.__tester.run(self.timer, self.options)
  File "/Users/hansje/projects/sockeye/moose/python/TestHarness/testers/bench.py", line 168, in run
    self.benchmark.run(timer, timeout=self.timeout)
  File "/Users/hansje/projects/sockeye/moose/python/TestHarness/testers/bench.py", line 197, in run
    self.test.run(timer, timeout=timeout - dt)
  File "/Users/hansje/projects/sockeye/moose/python/TestHarness/testers/bench.py", line 98, in run
    raise RuntimeError('command {} returned nonzero exit code'.format(cmd))
RuntimeError: command ['/Users/hansje/projects/sockeye/moose/test/moose_test-opt', '-i', '/Users/hansje/projects/sockeye/moose/test/tests/kernels/simple_transient_diffusion/simple_transient_diffusion.i', 'Mesh/nx=100', 'Mesh/ny=100', 'Executioner/num_steps=5', 'Outputs/console=false', 'Outputs/exodus=false', 'Outputs/csv=false', '--no-gdb-backtrace', 'UserObjects/perflog/type=PerflogDumper'] returned nonzero exit code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hansje/projects/sockeye/moose/python/TestHarness/schedulers/Scheduler.py", line 420, in runJob
    self.run(job) # Hand execution over to derived scheduler
  File "/Users/hansje/projects/sockeye/moose/python/TestHarness/schedulers/RunParallel.py", line 83, in run
    tester.setStatus(tester.error, 'PYTHON EXCEPTION')
AttributeError: 'SpeedTest' object has no attribute 'error'
```

## Impact
This prevents users from being able to use performance log data in their performance benchmarking.

**Comment by milljm** [comment]
This works for me?

```pre
❯ ./run_tests --run speedtests
kernels/simple_diffusion.diffusion_100x100 ....................................... RUNNING
kernels/simple_diffusion.diffusion_100x100 ................................. [FINISHED] OK
kernels/simple_transient_diffusion.trans_diffusion_100x100_t5 .................... RUNNING
kernels/simple_transient_diffusion.trans_diffusion_100x100_t5 .............. [FINISHED] OK
kernels/simple_diffusion.diffusion_200x200 ....................................... RUNNING
```
