### ISSUE TITLE
Cluster Launcher Error With No test_name

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#4554]
If you don't set the `test_name` parameter you get this:

```
JOB_NAME: bigpipe_001 JOB_ID:  TEST_NAME:
Traceback (most recent call last):
  File "/home/gastdr/projects/falcon/moose/framework/scripts/cluster_launcher.py", line 187, in <module>
    main()
  File "/home/gastdr/projects/falcon/moose/framework/scripts/cluster_launcher.py", line 184, in main
    cluster_launcher.run(dir, file, options)
  File "/home/gastdr/projects/falcon/moose/framework/scripts/cluster_launcher.py", line 154, in run
    self.createAndLaunchJob(template_dir, job_file, job, options)
  File "/home/gastdr/projects/falcon/moose/framework/scripts/cluster_launcher.py", line 138, in createAndLaunchJob
    job_instance.launch()
  File "/home/gastdr/projects/falcon/moose/framework/scripts/ClusterLauncher/PBSJob.py", line 115, in launch
    print 'JOB_NAME:', self.specs['job_name'], 'JOB_ID:', my_process.communicate()[0].split('.')[0], 'TEST_NAME:', self.specs['test_name']
  File "/home/gastdr/projects/falcon/moose/python/FactorySystem/InputParameters.py", line 38, in __getitem__
    return self.valid[key]
KeyError: 'test_name'
```

**Comment by permcody** [comment]
You're doing it wrong :smile:

**Comment by milljm** [comment]
@permcody Just going though some tickets I thought I could take ownership on... This issue looks like it can be closed

**Comment by permcody** [comment]
I don't think so, I believe it's still an issue. Yeah, Derek may have been doing it wrong but it should probably error out better or do something more intelligent than just crash.

**Comment by permcody** [comment]
Cluster launcher has been removed. Closing ticket.
