### ISSUE TITLE
gap_heat_transfer tests in modules do not work in parallel

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#4575]
Address sanitizer reports:

```
ASAN:SIGSEGV
=================================================================
==27049==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010b5422b1 bp 0x7fff56f5b820 sp 0x7fff56f5b520 T0)
    #0 0x10b5422b0 in Assembly::reinit(libMesh::Elem const*) (/Users/andrsd/workspace/moose/framework/libmoose-oprof.0.dylib+0x1ce2b0)
    #1 0x10b9ffc0b in FaceFaceConstraint::computeResidualSide() (/Users/andrsd/workspace/moose/framework/libmoose-oprof.0.dylib+0x68bc0b)
    #2 0x10b93641d in NonlinearSystem::constraintResiduals(libMesh::NumericVector<double>&, bool) (/Users/andrsd/workspace/moose/framework/libmoose-oprof.0.dylib+0x5c241d)
    #3 0x10b930fd6 in NonlinearSystem::computeResidualInternal(Moose::KernelType) (/Users/andrsd/workspace/moose/framework/libmoose-oprof.0.dylib+0x5bcfd6)
    #4 0x10b92f903 in NonlinearSystem::computeResidual(libMesh::NumericVector<double>&, Moose::KernelType) (/Users/andrsd/workspace/moose/framework/libmoose-oprof.0.dylib+0x5bb903)
    #5 0x10b663ba5 in FEProblem::computeResidualType(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, Moose::KernelType) (/Users/andrsd/workspace/moose/framework/libmoose-oprof.0.dylib+0x2efba5)
    #6 0x10b9213da in NonlinearSystem::solve() (/Users/andrsd/workspace/moose/framework/libmoose-oprof.0.dylib+0x5ad3da)
    #7 0x10b6614ab in FEProblem::solve() (/Users/andrsd/workspace/moose/framework/libmoose-oprof.0.dylib+0x2ed4ab)
    #8 0x10ba6ee3f in Steady::execute() (/Users/andrsd/workspace/moose/framework/libmoose-oprof.0.dylib+0x6fae3f)
    #9 0x10b8dc247 in MooseApp::executeExecutioner() (/Users/andrsd/workspace/moose/framework/libmoose-oprof.0.dylib+0x568247)
    #10 0x108ca3d2c in main (/Users/andrsd/workspace/moose/modules/combined/modules-oprof+0x100001d2c)
    #11 0x7fff91a385c8 in start (/usr/lib/system/libdyld.dylib+0x35c8)
    #12 0x3 (<unknown module>)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 Assembly::reinit(libMesh::Elem const*)
==27049==ABORTING
```

The MORTAR implementation has not been tested enough in parallel, so no surprise ;-)

**Comment by Andreas-Lepak** [comment]
@lindsayad can you close this? this issue isn't present anymore

**Comment by lindsayad** [comment]
closing as @Andreas-Lepak notes mortar works in parallel (most of the time 😄 )
