### ISSUE TITLE
Postprocessors in Peacock failing to render

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5993]
Sometimes they simply do not render at all.

```
mustafa$ Traceback (most recent call last):
  File "/Users/mustafa/projects/moose/gui/gui/PostprocessorWidget.py", line 161, in itemChangedOnPostProcessorList
    self.addPlot(text)
  File "/Users/mustafa/projects/moose/gui/gui/PostprocessorWidget.py", line 172, in addPlot
    self.plot_objects[plotName] = MPLPlotter(plot_data,plotName)
  File "/Users/mustafa/projects/moose/gui/utils/Plotter.py", line 49, in __init__
    self.canvas = PlotWidget()
  File "/Users/mustafa/projects/moose/gui/utils/Plotter.py", line 36, in __init__
    QtGui.QSizePolicy.Fixed)
TypeError: 'PySide.QtGui.QWidget.setSizePolicy' called with wrong argument types:
  PySide.QtGui.QWidget.setSizePolicy(Policy, Policy)
Supported signatures:
  PySide.QtGui.QWidget.setSizePolicy(PySide.QtGui.QSizePolicy)
  PySide.QtGui.QWidget.setSizePolicy(PySide.QtGui.QSizePolicy.Policy, PySide.QtGui.QSizePolicy.Policy)
```

See this discussion: https://groups.google.com/d/msgid/moose-users/715f8310-1fd0-4892-9224-a590cd2ea70c%40googlegroups.com

**Comment by permcody** [comment]
Closing. Postprocessors render correctly in the new Peacock
