### ISSUE TITLE
Threading problems with MOOSE Exception

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6191]
It appears that MOOSE exception is not thread-safe. If multiple threads throw at the same time there are thread errors that pop up in copying strings in the propagation of the error up the stack.

The most reliable way to replicate this is to use a LINUX system running three or more threads on this test:

```
tests/misc/exception/parallel_exception_initial_condition.i
```

**Comment by permcody** [comment]
BTW - I haven't seen any additional errors from parallel exception during residual or Jacobian evaluation after adding the shared has_thrown Boolean to the test class.

**Comment by friedmud** [comment]
What do you mean by "thread errors"?

**Comment by permcody** [comment]
Typically core dump from a multithreaded run on Linux

```
#0  0x00007f3789eb50d5 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007f3789eb87c0 in __GI_abort () at abort.c:120
#2  0x00007f3789ef261e in __libc_message (do_abort=2, fmt=0x7f3789ffcb40 "*** glibc detected *** %s: %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:201
#3  0x00007f3789efce16 in malloc_printerr (action=3, str=0x7f3789ffcd30 "double free or corruption (fasttop)", ptr=<optimized out>) at malloc.c:5047
#4  0x00007f378c4a4ff6 in std::string::assign(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f378cefd802 in ThreadedElementLoop<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> >::caughtMooseException (this=0x7f378642b958, 
    e=...) at /ssd/permcj/projects/moose/framework/include/base/ThreadedElementLoop.h:77
#6  0x00007f378cf40d94 in ThreadedElementLoopBase<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> >::operator() (this=0x7f378642b958, 
    range=..., bypass_threading=<optimized out>) at /ssd/permcj/projects/moose/framework/include/base/ThreadedElementLoopBase.h:177
#7  0x00007f378d00e7f9 in run_body (r=..., this=<optimized out>) at /opt/moose/tbb/include/tbb/parallel_reduce.h:156
#8  tbb::interface6::internal::partition_type_base<tbb::interface6::internal::auto_partition_type>::execute<tbb::interface6::internal::start_reduce<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, ComputeResidualThread, tbb::auto_partitioner const>, libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> > (this=0x7f378642b190, start=..., range=...) at /opt/moose/tbb/include/tbb/partitioner.h:277
#9  0x00007f378d00e952 in tbb::interface6::internal::start_reduce<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, ComputeResidualThread, tbb::auto_partitioner const>::execute (this=0x7f378642b140) at /opt/moose/tbb/include/tbb/parallel_reduce.h:168
#10 0x00007f378dbe015a in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7f3786423e00, parent=..., child=0x6)
    at ../../src/tbb/custom_scheduler.h:438
#11 0x00007f378dbddd31 in tbb::internal::arena::process (this=0x4108, s=...) at ../../src/tbb/arena.cpp:98
#12 0x00007f378dbdba75 in tbb::internal::market::process (this=0x4108, j=...) at ../../src/tbb/market.cpp:465
#13 0x00007f378dbd9254 in tbb::internal::rml::private_worker::run (this=0x4108) at ../../src/tbb/private_server.cpp:274
#14 0x00007f378dbd9186 in tbb::internal::rml::private_worker::thread_routine (arg=0x4108) at ../../src/tbb/private_server.cpp:231
#15 0x00007f378bfd9e9a in start_thread (arg=0x7f378208e700) at pthread_create.c:308
#16 0x00007f3789f728bd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#17 0x0000000000000000 in ?? ()
```

**Comment by permcody** [comment]
I suspect there's a problem with calling ThreadedLoop error handlers on multiple threads without mutexes. Yes, I can see that you aren't inspecting the values, but something is happening when you try to assign a string on two threads at the same time. I'll see if a local mutex can fix the problem.
