### ISSUE TITLE
Crash with TimeSequenceStepper during Restarts

### ISSUE THREAD

**Issue by mll36** [idaholab/moose#7493]
### Description of the enhancement or error report
On a restart, the TimeSequenceStepper drops the dt to the min instead of following the given time_sequence, ignoring the steps. If the dt is then increased to time between steps, it causes MOOSE to crash with the following error code:

/apps/local/easybuild/software/GCC/4.9.2/include/c++/4.9.2/debug/vector:357:
    error: attempt to subscript container with out-of-bounds index 15, but 
    container only holds 15 elements.

Objects involved in the operation:
sequence "this" @ 0x0x1214c10 {
  type = NSt7__debug6vectorIdSaIdEEE;
}

Program received signal SIGABRT, Aborted.
0x00002aaabb320885 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00002aaabb320885 in raise () from /lib64/libc.so.6
#1  0x00002aaabb321e61 in abort () from /lib64/libc.so.6
#2  0x00002aaabae1e865 in __gnu_debug::_Error_formatter::_M_error (this=0x7fffffff9cd0) at ../../../../../libstdc++-v3/src/c++11/debug.cc:782
#3  0x00002aaaab00f89f in std::__debug::vector<double, std::allocator<double> >::operator[] (this=0x1214c10, __n=15)
    at /apps/local/easybuild/software/GCC/4.9.2/include/c++/4.9.2/debug/vector:357
#4  0x00002aaab023c32e in TimeSequenceStepperBase::computeDT (this=0x1214db0) at .../moose/framework/src/timesteppers/TimeSequenceStepperBase.C:86
#5  0x00002aaab023c2e9 in TimeSequenceStepperBase::computeInitialDT (this=0x1214db0) at .../moose/framework/src/timesteppers/TimeSequenceStepperBase.C:80
#6  0x00002aaab022d582 in TimeStepper::computeStep (this=0x1214db0) at .../moose/framework/src/timesteppers/TimeStepper.C:78
#7  0x00002aaab04b83aa in Transient::computeDT (this=0x12bf500) at .../moose/framework/src/executioners/Transient.C:266
#8  0x00002aaab04b7e48 in Transient::init (this=0x12bf500) at .../moose/framework/src/executioners/Transient.C:205
#9  0x00002aaab00885a2 in MooseApp::executeExecutioner (this=0x77cb40) at .../moose/framework/src/base/MooseApp.C:421
#10 0x00002aaab008935c in MooseApp::run (this=0x77cb40) at .../moose/framework/src/base/MooseApp.C:578
#11 0x00000000004192a1 in main (argc=3, argv=0x7fffffffaf98) at .../bison/src/main.C:48

### Rationale for the enhancement or information for reproducing the error
Error can be reproduce by doing a restart with the TimeSequenceStepper.

### Identified impact
Affects all restarts with the TimeSequenceStepper. Other time steppers work fine, tested ok IterationAdaptiveDT, FunctionDT, and ConstantDT, behaving normally.

@permcody

**Comment by snschune** [comment]
I'll look at this one.
