### ISSUE TITLE
File not found during parallel runs

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#8486]
When running with parallel options with the TestHarness, we are running into an event where not all of the output are available for reading:

```pre
misc/check_error.bad_kernel_test.......................................................................... OK
misc/check_error.bad_kernel_var_test...................................................................... OK
Traceback (most recent call last):
  File "./run_tests", line 24, in <module>
    TestHarness.buildAndRun(sys.argv, app_name, MOOSE_DIR)
  File "/home/moosetest/civet/client_root_0/moose/python/TestHarness/TestHarness.py", line 36, in buildAndRun
    harness.findAndRunTests()
  File "/home/moosetest/civet/client_root_0/moose/python/TestHarness/TestHarness.py", line 233, in findAndRunTests
    self.runner.run(tester, command)
  File "/home/moosetest/civet/client_root_0/moose/python/TestHarness/RunParallel.py", line 79, in run
    self.startReadyJobs(slot_check)
  File "/home/moosetest/civet/client_root_0/moose/python/TestHarness/RunParallel.py", line 150, in startReadyJobs
    self.run(tester, command, recurse=False, slot_check=slot_check)
  File "/home/moosetest/civet/client_root_0/moose/python/TestHarness/RunParallel.py", line 103, in run
    self.spinwait()
  File "/home/moosetest/civet/client_root_0/moose/python/TestHarness/RunParallel.py", line 221, in spinwait
    self.returnToTestHarness(job_index)
  File "/home/moosetest/civet/client_root_0/moose/python/TestHarness/RunParallel.py", line 174, in returnToTestHarness
    output += self.getOutputFromFiles(tester)
  File "/home/moosetest/civet/client_root_0/moose/python/TestHarness/RunParallel.py", line 159, in getOutputFromFiles
    with open(file_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/moosetest/civet/client_root_0/moose/test/tests/misc/check_error/Badd_material_test.processor.1'
ERROR: exiting with code 1
```
Upon logging into the machine in question, the file is indeed available. This seems to only be replicable on my CentOS 7 VM. Each time being a different test.

**Comment by permcody** [comment]
If this is only happening with parallel jobs (`-p 2`) and only on CentOS (gathered this information from Jason) there may be another explanation. It might be that when one process dies that's part of an MPI run, there's no guarantee that the other process will immediately be dead one the first is reported as dead. We need to see if there might be a more robust way of checking for all processes being dead before trying to read their individual outputs. 

Barring that, we could boot and just check to see if all outputs are available and if not, start a second "wait for files" timeout for which we keep checking for job completion.

**Comment by milljm** [comment]
I came into work this morning where this same error has presented itself on Fedora 25.
https://www.moosebuild.org/job/66528/

**Comment by permcody** [comment]
On Wed, Feb 8, 2017 at 6:47 AM Jason Miller <notifications@github.com>
wrote:

> I came into work this morning
>

Well this was your first problem...
