### ISSUE TITLE
Moosedocs.py create pdf not working

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#9140]
### Description of the enhancement or error report
I don't know if it is just me, but when I try to build a pdf using `moosedocs.py` I get an error that an extension (`materialize`) could not be loaded. 

### Rationale for the enhancement or information for reproducing the error

The full error message I get is
```
(docs) SHAMMY-CL:docs gre462$ ./moosedocs.py latex examples/report.md 
Traceback (most recent call last):
  File "./moosedocs.py", line 21, in <module>
    sys.exit(main.run())
  File "/Users/gre462/Documents/MOOSE/projects/moose/python/MooseDocs/main.py", line 192, in run
    retcode = commands.latex(**options) #pylint: disable=assignment-from-none
  File "/Users/gre462/Documents/MOOSE/projects/moose/python/MooseDocs/commands/latex.py", line 137, in latex
    parser = MooseDocs.MooseMarkdown(extensions=config.keys(), extension_configs=config)
  File "/Users/gre462/Documents/MOOSE/projects/moose/python/MooseDocs/MooseMarkdown.py", line 46, in __init__
    extension_configs=extension_configs)
  File "/Users/gre462/.conda/envs/docs/lib/python2.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/Users/gre462/.conda/envs/docs/lib/python2.7/site-packages/markdown/__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/Users/gre462/.conda/envs/docs/lib/python2.7/site-packages/markdown/__init__.py", line 264, in build_extension
    module = importlib.import_module(module_name_old_style)
  File "/Users/gre462/.conda/envs/docs/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Failed loading extension 'MooseDocs.extensions.materialize' from 'MooseDocs.extensions.materialize', 'markdown.extensions.MooseDocs.extensions.materialize' or 'mdx_MooseDocs.extensions.materialize'
```

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by brianmoose** [comment]
It is not just you, I get the same error. I will look into it.
